### ISSUE TITLE
[Feat] Todo 엔티티 관련 클래스 및 인터페이스 생성

### ISSUE THREAD

**Issue by hunzzzzz** [hunzzzzz/todo-application#1]
- [x] BaseEntity 생성 -> createdAt, updatedAt
- [x] Todo 엔티티 생성 -> id, title, content, date
- [x] TodoController, TodoService, TodoRepository 생성
